name: Nightly build of fork

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
    - name: Install dependencies
      run: sudo apt-get install make python gcc git bison
    - name: Checkout RGBDS
      uses: actions/checkout@v2
      with:
        repository: gbdev/rgbds
        ref: v0.5.1
        path: rgbds
    - name: Install RGBDS
      working-directory: rgbds
      run: sudo make install
    - name: Checkout Polished Crystal
      uses: actions/checkout@v2
      with:
        path: polishedcrystal
    - name: Create hash file for graphcis
      run: |
        find ./polishedcrystal -name '*.png' -print0 | \
          LC_ALL=C sort -z | \
          tar --null --files-from=- --mtime='2015-10-21 00:00Z' --owner=0 --group=0 --numeric-owner --format=gnu -cf 'gfx_collection.tar'
    - name: Check cache for graphics
      uses: actions/cache@v2
      with:
        # Cache lz compressed graphics
        path: ./polishedcrystal/**/*.lz
        key: ${{ runner.os }}-build-${{ hashFiles('gfx_collection.tar') }}
    - name: Build Polished Crystal
      working-directory: polishedcrystal
      run: |
        mkdir build
        make -j4
        mv polishedcrystal-3.0.0-beta.gbc build/polishedcrystal-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polishedcrystal-3.0.0-beta.sym
        make tidy
        make -j4 singlespeed
        mv polishedcrystal-3.0.0-beta.gbc build/polishedcrystal-singlespeed-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polishedcrystal-singlespeed-3.0.0-beta.sym
        make tidy
        make -j4 singlespeed faithful
        mv polishedcrystal-3.0.0-beta.gbc build/polishedcrystal-singlespeed-faithful-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polishedcrystal-singlespeed-faithful-3.0.0-beta.sym
        make tidy
        make -j4 singlespeed debug
        mv polishedcrystal-3.0.0-beta.gbc build/polisheddebug-singlespeed-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polisheddebug-singlespeed-3.0.0-beta.sym
        make tidy
        make -j4 singlespeed faithful debug
        mv polishedcrystal-3.0.0-beta.gbc build/polisheddebug-singlespeed-faithful-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polisheddebug-singlespeed-faithful-3.0.0-beta.sym
        make tidy
        make bsp
        mv polishedcrystal-3.0.0-beta.bsp build/polishedcrystal-savepatch-3.0.0-beta.bsp
    - name: Upload build as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build-Output
        path: polishedcrystal/build/
        if-no-files-found: error
