name: Nightly build of fork

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment variables
      run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        sudo apt-get install make python gcc git bison
        git clone -b v0.5.1 --depth=1 https://github.com/gbdev/rgbds
        pushd rgbds
        sudo make install
        popd
    - name: Build Rangi42/polishedcrystal
      run: |
        git clone https://github.com/Rangi42/polishedcrystal.git
        pushd polishedcrystal
        mkdir build
        make -j4
        mv polishedcrystal-3.0.0-beta.gbc build/polishedcrystal-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polishedcrystal-3.0.0-beta.sym
        make tidy
        make -j4 faithful
        mv polishedcrystal-3.0.0-beta.gbc build/polishedcrystal-faithful-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polishedcrystal-faithful-3.0.0-beta.sym
        make tidy
        make -j4 debug
        mv polishedcrystal-3.0.0-beta.gbc build/polisheddebug-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polisheddebug-3.0.0-beta.sym
        make tidy
        make -j4 faithful debug
        mv polishedcrystal-3.0.0-beta.gbc build/polisheddebug-faithful-3.0.0-beta.gbc
        mv polishedcrystal-3.0.0-beta.sym build/polisheddebug-faithful-3.0.0-beta.sym
        make tidy
        make bsp
        mv polishedcrystal-3.0.0-beta.bsp build/polishedcrystal-savepatch-3.0.0-beta.bsp
        popd
    - name: Upload build as artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: polishedcrystal/build/
